INSERT INTO products (product_name, product_category, product_description, product_price, product_stock, product_image) VALUES
('Women''s Short Sleeve Shirt', 'women''s clothing', 'Double layered placket, collar and cuff for a more structured look. This shirt combines timeless style with comfort. Stretch, opaque fabric.', 14.99, 0, 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg'),
('WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'electronics', 'Expand your PS4 gaming experience, Play anywhere', 114.55, 0, 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg'),
('Acrylic Coffin False Nail Tips', 'women''s clothing', 'Diy nail art: great for nails salon,professional nail artists diy nail art,acrylic nails, gel nails, false nails, nail tips, press on nails, nail art stickers, nail decor, nail decorations', 7.99, 0, 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UL640_QL65_ML3_.jpg'),
('SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'electronics', 'Easy upgrade for faster boot-up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive. Based on published specifications and internal benchmarking tests using PCMark vantage scores.)', 109, 0, 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg'),
('USB-C to USB 3.0 Adapter (3-Pack)', 'electronics', 'USB C to USB adapter connects type-c devices (MacBook Pro, Chromebook Pixel, Galaxy Note 7, etc.) to USB-A devices (laptops, hard drives, power banks, wall/car chargers, etc.)', 9.85, 0, 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg'),
('BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats', 'women''s clothing', 'Note:The Jackets is US standard size,Please choose size as your usual wear', 56.99, 0, 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg'),
('Samsung Galaxy Tab A 8.0"', 'electronics', '1280 x 800 Resolution Display, Quad-Core Processor, 16GB Storage, 1.5GB RAM, micro-SD Card Slot (Up to 256GB), Headphone Jack, 5MP Rear Camera, 2MP Front Camera, Android 7.0 OS', 149.99, 0, 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg'),
('BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats', 'women''s clothing', 'Note:The Jackets is US standard size,Please choose size as your usual wear', 56.99, 0, 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg'),
('BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats', 'women''s clothing', 'Note:The Jackets is US standard size,Please choose size as your usual wear', 56.99, 0, 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg'),
('Columbia Casual Jacket for Men, Cotton, Zippered', 'men''s clothing', 'Great for Casual and Sport Wear, Going Out, School, Vacation or outdoor activities.', 59, 0, 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg');
